# Generated by Django 5.2 on 2026-02-18 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0006_student_is_rejected'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_percentage', models.FloatField()),
                ('internal_marks', models.FloatField()),
                ('assignment_marks', models.FloatField()),
                ('result', models.CharField(max_length=10)),
                ('advice', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
