# Generated by Django 5.2 on 2026-02-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
