# Generated by Django 5.2 on 2026-02-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(choices=[('B-I', 'Batch I'), ('B-II', 'Batch II'), ('B-III', 'Batch III')], default='B-I', max_length=10),
        ),
    ]
