# Generated by Django 5.2 on 2026-02-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_is_approved_student_registered_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
