# Generated by Django 5.2 on 2026-02-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('FY', 'First Year'), ('SY', 'Second Year'), ('TY', 'Third Year')], default='FY', max_length=2),
        ),
    ]
