# Generated by Django 5.2 on 2026-02-16 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_timetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
