# Generated by Django 5.2 on 2026-02-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_subject_batch'),
        ('students', '0006_student_is_rejected'),
        ('teachers', '0007_teacher_gender_alter_teacher_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalmarks',
            name='marks',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='internalmarks',
            unique_together={('student', 'subject')},
        ),
    ]
