# Generated by Django 5.2 on 2026-02-16 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_timetable_options_alter_timetable_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['period_number']},
        ),
    ]
