# Generated by Django 5.2 on 2026-02-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_timetable_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='batch',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
