# Generated by Django 5.2 on 2026-02-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_timetable_batch'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['day', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='batch',
            field=models.CharField(blank=True, choices=[('B-I', 'Batch I'), ('B-II', 'Batch II'), ('B-III', 'Batch III')], max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'timetable', 'date')},
        ),
    ]
