# Generated by Django 5.2 on 2026-02-16 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_remove_attendance_time_alter_attendance_timetable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='timetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.timetable'),
        ),
    ]
