# Generated by Django 5.2 on 2026-02-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendance_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='batch',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
